// Copyright (c) roydukkey. All rights reserved.
// Licensed under the MIT. See LICENSE file in the project root for full license information.


const packages = [
	'break',
	'color',
	'exception',
	'list',
	'map',
	'math',
	'meta',
	'string'
];


const sidebars = {

	docsSidebar: [
		'docs/intro',
		'docs/install',
		{
			type: 'category',
			label: 'Spec',
			collapsed: false,
			items: [
				'docs/reference-functions',
				'docs/compare-logic',
				'docs/list-modifiers'
			]
		},
		'docs/advanced'
	],

	apiSidebar: [
		'api/overview',
		...packages.map((package) => (
			{
				type: 'ref',
				label: `@sass-fairy/${package}`,
				id: `api/${package}/overview`
			}
		))
	],

	...Object.fromEntries(packages.map((package) => [
		`${package}Sidebar`,
		[
			{
				type: 'ref',
				id: 'api/overview'
			},
			{
				type: 'category',
				label: `@sass-fairy/${package}`,
				items: [
					{
						type: 'autogenerated',
						dirName: `api/${package}`
					}
				]
			}
		]
	]))

};


module.exports = sidebars;
